# Generated by Django 2.0.6 on 2020-09-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=66)),
                ('pwd', models.CharField(max_length=66)),
                ('age', models.CharField(max_length=66)),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('img', models.ImageField(default='static/img/33.jpg', upload_to='img')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
                'db_table': 'tb_manage',
            },
        ),
    ]
